genome: /home/faraut/dynawork/SeqOccin/data/genome/perca_flavescens/Perca_flavescens.PFLA1.1.dna.toplevel.okseqids.fa.gz
samples: samples.tsv
workdir: /work/project/dynagen/sdjebali/SeqOccIn/snakemake/pipeline/seqoccinlr/perca_flavescens
nbsampread: 1000
nbsimread: 100000
